# Generated by Django 5.0.1 on 2024-01-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('reservation_date', models.DateField()),
                ('reservation_slot', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
